@{
    RootModule        = 'InventorySync.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '89d605f0-44cb-497c-a664-96c6c13d2bfc'
    Author            = 'PALP inventory sync'
    PowerShellVersion = '7.6'
    FunctionsToExport = @(
        'Get-InventorySyncConfiguration'
        'Get-InventoryAccessToken'
        'Clear-InventoryTokenCache'
        'Invoke-InventoryHttpRequest'
        'Get-DataversePagedRecords'
        'Invoke-ResourceGraphPagedQuery'
        'Get-AgentBuilderAgents'
        'Get-RpaEnvironmentPlan'
        'Get-RpaDesktopFlows'
        'Invoke-RpaEnvironmentFanOut'
        'New-InventoryComponentId'
        'New-InventoryComponentReconciliationPlan'
        'New-AgentComponentCreatePlan'
        'Write-DataverseBatch'
        'Start-InventorySyncRun'
        'Complete-InventorySyncRun'
        'Write-InventorySyncLog'
        'Write-AgentSyncSkippedRun'
        'Write-RpaSyncSkippedRun'
        'Invoke-AgentCreateSync'
        'Invoke-AgentSync'
        'Invoke-RpaSync'
        'Write-InventoryTrace'
        'Get-InventoryOperationId'
        'Invoke-InventorySyncTimer'
        'Invoke-InventorySyncOrchestrator'
        'Invoke-InventorySyncActivity'
        'Write-InventorySyncSkippedRun'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
